import {
  ArrayListJentisPlaceholder,
  GuiListJentisPlaceholder,
  JentisFunction,
  JentisPlaceholder,
  NormalJentisPlaceholder,
} from "../jentis-types";
import { generateId } from "../utils";
import { PixelBuilderElement } from "./types";

const exampleFunction: JentisFunction = {
  id: generateId(),
  name: "Anonymize",
};

export const functions: JentisFunction[] = [exampleFunction];

const normalExamplePlaceholder: NormalJentisPlaceholder = {
  type: undefined,
  id: generateId(),
  name: "Href",
  desc: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
  group: "group",
  optional: false,
  hash: false,
  value: "jentis.core.jtm.plugin.variable.product_quantity",
};

const guiListExamplePlaceholder: GuiListJentisPlaceholder = {
  type: "guilist",
  id: generateId(),
  name: "Guilist",
  desc: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
  group: "group",
  optional: false,
  entries: {},
  payload: [],
  stream: [],
};

const arrayListExamplePlaceholder: ArrayListJentisPlaceholder = {
  type: "arraylist",
  id: generateId(),
  name: "Arraylist",
  desc: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
  group: "group",
  optional: false,
  filter: { value: "", operator: "eq", variable: "jentis.core.jtm.plugin.variable.product_type" },
  payload: [],
  stream: [],
};

export const placeholder: JentisPlaceholder[] = [
  normalExamplePlaceholder,
  guiListExamplePlaceholder,
  arrayListExamplePlaceholder,
];

export const metaPixelBasicPayload: PixelBuilderElement[] = [
  {
    id: "1hkrzio35yq",
    type: "TEXT",
    value: '{"partner_agent": "pljentis-1.2",',
  },
  {
    id: "0zi3pcr1bes",
    type: "PLACEHOLDER",
    placeholder: normalExamplePlaceholder,
    optional: false,
    stringBefore: '"event_name":"',
    stringAfter: 'CustomizeProduct",',
  },
];

export const metaPixelPayload: PixelBuilderElement[] = [
  {
    id: "9hkrzib35yq",
    type: "TEXT",
    value: '"data":',
    color: undefined,
  },
  {
    id: "39swi09lv9f",
    type: "TEXT",
    value: "[",
    color: "orange",
  },
  {
    id: "3uzceyltcmh",
    type: "TEXT",
    value: "{",
    color: "blue",
  },
  {
    id: "0zi3pcr1bed",
    type: "PLACEHOLDER",
    placeholder: normalExamplePlaceholder,
    optional: false,
    stringBefore: '"event_name":"',
    stringAfter: 'CustomizeProduct",',
  },
  {
    id: "j50u2wngobo",
    type: "PLACEHOLDER",
    placeholder: normalExamplePlaceholder,
    optional: false,
    stringBefore: '"event_time":"',
    stringAfter: '",',
  },
  {
    id: "l646tryrfh",
    type: "PLACEHOLDER",
    placeholder: normalExamplePlaceholder,
    optional: false,
    stringBefore: '"event_id":"',
    stringAfter: '",',
  },
  {
    id: "hh4nhrar36u",
    type: "PLACEHOLDER",
    placeholder: normalExamplePlaceholder,
    optional: false,
    stringBefore: '"event_source_url":"',
    stringAfter: '",',
  },
  {
    id: "1tb48rorxre",
    type: "PLACEHOLDER",
    placeholder: normalExamplePlaceholder,
    optional: false,
    stringBefore: '"action_source":"',
    stringAfter: '",',
  },
  {
    id: "ox3uh789vp",
    type: "PLACEHOLDER",
    placeholder: normalExamplePlaceholder,
    optional: true,
    stringBefore: '"opt_out":"',
    stringAfter: '",',
  },
  {
    id: "1i4q9o60dl4",
    type: "TEXT",
    value: '"user_data":',
    color: undefined,
  },
  {
    id: "9pujruubrqp",
    type: "TEXT",
    value: "{",
    color: "#00d200",
  },
  {
    id: "0u6lew7ogc8",
    type: "CONTENT_BLOCK",
    label: "Content Block",
    children: [
      {
        id: "900894oatjv",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"em":"',
        stringAfter: '",',
      },
      {
        id: "22mpwdqs0yk",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"ph":"',
        stringAfter: '",',
      },
      {
        id: "jxbka4dmlan",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"ge":"',
        stringAfter: '",',
      },
      {
        id: "3vulxx80en",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"db":"',
        stringAfter: '",',
      },
      {
        id: "qpd6ouzza8p",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"ln":"',
        stringAfter: '",',
      },
      {
        id: "5bds1w1l4rg",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"fn":"',
        stringAfter: '",',
      },
      {
        id: "rfbm9oielx",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"ct":"',
        stringAfter: '",',
      },
      {
        id: "74gf8gv7l9o",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"st":"',
        stringAfter: '",',
      },
      {
        id: "umkiw0ybfpm",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"zp":"',
        stringAfter: '",',
      },
      {
        id: "ue0qsuhpw7s",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"country":"',
        stringAfter: '",',
      },
      {
        id: "y62s092m9j",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"subscription_id":"',
        stringAfter: '",',
      },
      {
        id: "9vy4tvj4ht5",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"lead_id":"',
        stringAfter: '",',
      },
      {
        id: "0aimyff42dtq",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"fb_login_id":"',
        stringAfter: '",',
      },
      {
        id: "4eb448vh2lw",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"fb_external_id":"',
        stringAfter: '",',
      },
      {
        id: "ruhfgguc3xr",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"fbc":"',
        stringAfter: '",',
      },
      {
        id: "n2w4iswub2",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: '"fbp":"',
        stringAfter: '",',
      },
      {
        id: "jlv5t4upc4",
        type: "FUNCTION",
        fn: exampleFunction,
        stringBefore: '"client_ip_address":"',
        stringAfter: '",',
        children: [
          {
            id: "2pxc58qy73y",
            type: "PLACEHOLDER",
            placeholder: normalExamplePlaceholder,
            optional: false,
            stringBefore: undefined,
            stringAfter: undefined,
          },
        ],
        childrenId: "ly68f6o5zs",
      },
      {
        id: "edv27xb1lee",
        type: "FUNCTION",
        fn: exampleFunction,
        stringBefore: '"client_user_agent":"',
        stringAfter: '"',
        children: [
          {
            id: "pylh40pc4xc",
            type: "PLACEHOLDER",
            placeholder: normalExamplePlaceholder,
            optional: false,
            stringBefore: undefined,
            stringAfter: undefined,
          },
        ],
        childrenId: "3wkjfh6osky",
      },
    ],
    childrenId: "yx5zeyk492b",
  },
  {
    id: "cpcz9nh7vd4",
    type: "TEXT",
    value: "}",
    color: "#00d200",
  },
  {
    id: "b3en0bt2oho",
    type: "TEXT",
    value: ",",
    color: undefined,
  },
  {
    id: "y617r6q91t",
    type: "TEXT",
    value: '"custom_data":',
    color: undefined,
  },
  {
    id: "ghrvozrxgyu",
    type: "TEXT",
    value: "{",
    color: "red",
  },
  {
    id: "lc7cerp3ddo",
    type: "CONTENT_BLOCK",
    label: "Content Block",
    children: [
      {
        id: "ph4etndzmze",
        type: "TEXT",
        value: '"jentis":"true"',
        color: undefined,
      },
      {
        id: "1bhipv47b3e",
        type: "PLACEHOLDER",
        placeholder: guiListExamplePlaceholder,
        optional: false,
        stringBefore: undefined,
        stringAfter: undefined,
      },
      {
        id: "g20x9pwah0d",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: ',"content_category":"',
        stringAfter: '"',
      },
      {
        id: "immf2bgh4tg",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: ',"content_name":"',
        stringAfter: '"',
      },
      {
        id: "0jh13qew2un",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: ',"currency":"',
        stringAfter: '"',
      },
      {
        id: "jcsf0zpcw5",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: ',"predicted_ltv":"',
        stringAfter: '"',
      },
      {
        id: "t15mo5u5z7",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: ',"value":"',
        stringAfter: '"',
      },
      {
        id: "er1hc0svuk",
        type: "PLACEHOLDER",
        placeholder: normalExamplePlaceholder,
        optional: true,
        stringBefore: ',"content_type":"',
        stringAfter: '"',
      },
      {
        id: "zw61uvu8mz",
        type: "TEXT",
        value: ",",
        color: undefined,
      },
      {
        id: "njo8b0clmbl",
        type: "TEXT",
        value: '"content_ids":',
        color: undefined,
      },
      {
        id: "vup03o1q8u",
        type: "TEXT",
        value: "[",
        color: "violet",
      },
      {
        id: "xe01e5f5bds",
        type: "PLACEHOLDER",
        placeholder: arrayListExamplePlaceholder,
        optional: false,
        stringBefore: undefined,
        stringAfter: undefined,
      },
      {
        id: "76sepmw8wm4",
        type: "TEXT",
        value: "]",
        color: "violet",
      },
      {
        id: "t1vwexe3fvi",
        type: "TEXT",
        value: ",",
        color: undefined,
      },
      {
        id: "7tzvrdqnm6t",
        type: "TEXT",
        value: '"contents":',
        color: undefined,
      },
      {
        id: "os34n93345g",
        type: "TEXT",
        value: "[",
        color: "violet",
      },
      {
        id: "9np1onp3ng",
        type: "PLACEHOLDER",
        placeholder: arrayListExamplePlaceholder,
        optional: false,
        stringBefore: undefined,
        stringAfter: undefined,
      },
      {
        id: "c8dnjzogssq",
        type: "TEXT",
        value: "]",
        color: "violet",
      },
    ],
    childrenId: "fykx7w8nlna",
  },
  {
    id: "04ps9uqu6vkc",
    type: "TEXT",
    value: "}",
    color: "red",
  },
  {
    id: "56oyd0h0ni7",
    type: "TEXT",
    value: "}",
    color: "blue",
  },
  {
    id: "fb3it8phkbv",
    type: "TEXT",
    value: "]",
    color: "orange",
  },
  {
    id: "qtpztdz0gw",
    type: "TEXT",
    value: "}",
    color: undefined,
  },
];
