import { PixelBuilderElement } from "./types";

export const metaPixelBasicPayload: PixelBuilderElement[] = [
  {
    id: "1hkrzio35yq",
    type: "TEXT",
    value: '{"partner_agent": "pljentis-1.2",',
    label: '{"partner_agent": "pljentis-1.2",',
    color: undefined,
  },
];

export const metaPixelPayload: PixelBuilderElement[] = [
  {
    id: "9hkrzib35yq",
    type: "TEXT",
    value: '"data":',
    label: '"data":',
    color: undefined,
  },
  {
    id: "39swi09lv9f",
    type: "TEXT",
    value: "[",
    label: "[",
    color: "orange",
  },
  {
    id: "3uzceyltcmh",
    type: "TEXT",
    value: "{",
    label: "{",
    color: "blue",
  },
  {
    id: "0zi3pcr1bed",
    type: "PLACEHOLDER",
    label: "Event Name Prefix",
    placeholder: {
      id: "4zafk5w56ds",
      label: "Event Name Prefix",
    },
    optional: false,
    stringBefore: '"event_name":"',
    stringAfter: 'CustomizeProduct",',
  },
  {
    id: "j50u2wngobo",
    type: "PLACEHOLDER",
    label: "Event Time",
    placeholder: {
      id: "q0x0qnogrk",
      label: "Event Time",
    },
    optional: false,
    stringBefore: '"event_time":"',
    stringAfter: '",',
  },
  {
    id: "l646tryrfh",
    type: "PLACEHOLDER",
    label: "Event Id",
    placeholder: {
      id: "j7i9es2y8e",
      label: "Event Id",
    },
    optional: false,
    stringBefore: '"event_id":"',
    stringAfter: '",',
  },
  {
    id: "hh4nhrar36u",
    type: "PLACEHOLDER",
    label: "Href",
    placeholder: {
      id: "tu8q12ty6wb",
      label: "Href",
    },
    optional: false,
    stringBefore: '"event_source_url":"',
    stringAfter: '",',
  },
  {
    id: "1tb48rorxre",
    type: "PLACEHOLDER",
    label: "Action Source",
    placeholder: {
      id: "voehi8zlfh",
      label: "Action Source",
    },
    optional: false,
    stringBefore: '"action_source":"',
    stringAfter: '",',
  },
  {
    id: "ox3uh789vp",
    type: "PLACEHOLDER",
    label: "Opt Out",
    placeholder: {
      id: "ulzlsknnow",
      label: "Opt Out",
    },
    optional: true,
    stringBefore: '"opt_out":"',
    stringAfter: '",',
  },
  {
    id: "1i4q9o60dl4",
    type: "TEXT",
    value: '"user_data":',
    label: '"user_data":',
    color: undefined,
  },
  {
    id: "9pujruubrqp",
    type: "TEXT",
    value: "{",
    label: "{",
    color: "#00d200",
  },
  {
    id: "0u6lew7ogc8",
    type: "CONTENT_BLOCK",
    label: "Content Block",
    children: [
      {
        id: "900894oatjv",
        type: "PLACEHOLDER",
        label: "Email",
        placeholder: {
          id: "y6c7kx0a8a8",
          label: "Email",
        },
        optional: true,
        stringBefore: '"em":"',
        stringAfter: '",',
      },
      {
        id: "22mpwdqs0yk",
        type: "PLACEHOLDER",
        label: "Phone",
        placeholder: {
          id: "pco3lkb2d3r",
          label: "Phone",
        },
        optional: true,
        stringBefore: '"ph":"',
        stringAfter: '",',
      },
      {
        id: "jxbka4dmlan",
        type: "PLACEHOLDER",
        label: "Gender",
        placeholder: {
          id: "yt1uyj94ha",
          label: "Gender",
        },
        optional: true,
        stringBefore: '"ge":"',
        stringAfter: '",',
      },
      {
        id: "3vulxx80en",
        type: "PLACEHOLDER",
        label: "Day Of Birth",
        placeholder: {
          id: "ou8jisqdhfc",
          label: "Day Of Birth",
        },
        optional: true,
        stringBefore: '"db":"',
        stringAfter: '",',
      },
      {
        id: "qpd6ouzza8p",
        type: "PLACEHOLDER",
        label: "Last Name",
        placeholder: {
          id: "vxfavini7re",
          label: "Last Name",
        },
        optional: true,
        stringBefore: '"ln":"',
        stringAfter: '",',
      },
      {
        id: "5bds1w1l4rg",
        type: "PLACEHOLDER",
        label: "First Name",
        placeholder: {
          id: "zzarpkj5vib",
          label: "First Name",
        },
        optional: true,
        stringBefore: '"fn":"',
        stringAfter: '",',
      },
      {
        id: "rfbm9oielx",
        type: "PLACEHOLDER",
        label: "City",
        placeholder: {
          id: "4cvl43jvxyv",
          label: "City",
        },
        optional: true,
        stringBefore: '"ct":"',
        stringAfter: '",',
      },
      {
        id: "74gf8gv7l9o",
        type: "PLACEHOLDER",
        label: "Street",
        placeholder: {
          id: "5t88zqokxud",
          label: "Street",
        },
        optional: true,
        stringBefore: '"st":"',
        stringAfter: '",',
      },
      {
        id: "umkiw0ybfpm",
        type: "PLACEHOLDER",
        label: "ZIP",
        placeholder: {
          id: "6ziv2bigrg",
          label: "ZIP",
        },
        optional: true,
        stringBefore: '"zp":"',
        stringAfter: '",',
      },
      {
        id: "ue0qsuhpw7s",
        type: "PLACEHOLDER",
        label: "Country",
        placeholder: {
          id: "wacofvqvy9l",
          label: "Country",
        },
        optional: true,
        stringBefore: '"country":"',
        stringAfter: '",',
      },
      {
        id: "y62s092m9j",
        type: "PLACEHOLDER",
        label: "Subscription ID",
        placeholder: {
          id: "zngauu42ip",
          label: "Subscription ID",
        },
        optional: true,
        stringBefore: '"subscription_id":"',
        stringAfter: '",',
      },
      {
        id: "9vy4tvj4ht5",
        type: "PLACEHOLDER",
        label: "Lead ID",
        placeholder: {
          id: "2l1kml23xe9",
          label: "Lead ID",
        },
        optional: true,
        stringBefore: '"lead_id":"',
        stringAfter: '",',
      },
      {
        id: "0aimyff42dtq",
        type: "PLACEHOLDER",
        label: "FB Login ID",
        placeholder: {
          id: "obws4yx5wq",
          label: "FB Login ID",
        },
        optional: true,
        stringBefore: '"fb_login_id":"',
        stringAfter: '",',
      },
      {
        id: "4eb448vh2lw",
        type: "PLACEHOLDER",
        label: "External ID",
        placeholder: {
          id: "jpqw31v01fa",
          label: "External ID",
        },
        optional: true,
        stringBefore: '"fb_external_id":"',
        stringAfter: '",',
      },
      {
        id: "ruhfgguc3xr",
        type: "PLACEHOLDER",
        label: "Click ID",
        placeholder: {
          id: "n2ii897tbx",
          label: "Click ID",
        },
        optional: true,
        stringBefore: '"fbc":"',
        stringAfter: '",',
      },
      {
        id: "n2w4iswub2",
        type: "PLACEHOLDER",
        label: "Browser ID",
        placeholder: {
          id: "j7arvi0qj3",
          label: "Browser ID",
        },
        optional: true,
        stringBefore: '"fbp":"',
        stringAfter: '",',
      },
      {
        id: "jlv5t4upc4",
        type: "FUNCTION",
        fn: {
          id: "oiilwhg576",
          label: "Anonymize",
        },
        label: "Anonymize",
        stringBefore: '"client_ip_address":"',
        stringAfter: '",',
        children: [
          {
            id: "2pxc58qy73y",
            type: "PLACEHOLDER",
            label: "Client IP Address",
            placeholder: {
              id: "pyf308fxgbe",
              label: "Client IP Address",
            },
            optional: false,
            stringBefore: undefined,
            stringAfter: undefined,
          },
        ],
        childrenId: "ly68f6o5zs",
      },
      {
        id: "edv27xb1lee",
        type: "FUNCTION",
        fn: {
          id: "ow64vynhei",
          label: "Anonymize",
        },
        label: "Anonymize",
        stringBefore: '"client_user_agent":"',
        stringAfter: '"',
        children: [
          {
            id: "pylh40pc4xc",
            type: "PLACEHOLDER",
            label: "Client User Agent",
            placeholder: {
              id: "w6lapc8ama",
              label: "Client User Agent",
            },
            optional: false,
            stringBefore: undefined,
            stringAfter: undefined,
          },
        ],
        childrenId: "3wkjfh6osky",
      },
    ],
    childrenId: "yx5zeyk492b",
  },
  {
    id: "cpcz9nh7vd4",
    type: "TEXT",
    value: "}",
    label: "}",
    color: "#00d200",
  },
  {
    id: "b3en0bt2oho",
    type: "TEXT",
    value: ",",
    label: ",",
    color: undefined,
  },
  {
    id: "y617r6q91t",
    type: "TEXT",
    value: '"custom_data":',
    label: '"custom_data":',
    color: undefined,
  },
  {
    id: "ghrvozrxgyu",
    type: "TEXT",
    value: "{",
    label: "{",
    color: "red",
  },
  {
    id: "lc7cerp3ddo",
    type: "CONTENT_BLOCK",
    label: "Content Block",
    children: [
      {
        id: "ph4etndzmze",
        type: "TEXT",
        value: '"jentis":"true"',
        label: '"jentis":"true"',
        color: undefined,
      },
      {
        id: "1bhipv47b3e",
        type: "PLACEHOLDER",
        label: "Custom Parameters",
        placeholder: {
          id: "8boefzbaocy",
          label: "Custom Parameters",
        },
        optional: false,
        stringBefore: undefined,
        stringAfter: undefined,
      },
      {
        id: "g20x9pwah0d",
        type: "PLACEHOLDER",
        label: "Content Category",
        placeholder: {
          id: "qvoizx4vmvq",
          label: "Content Category",
        },
        optional: true,
        stringBefore: ',"content_category":"',
        stringAfter: '"',
      },
      {
        id: "immf2bgh4tg",
        type: "PLACEHOLDER",
        label: "Content Name",
        placeholder: {
          id: "1vkbplvsoiz",
          label: "Content Name",
        },
        optional: true,
        stringBefore: ',"content_name":"',
        stringAfter: '"',
      },
      {
        id: "0jh13qew2un",
        type: "PLACEHOLDER",
        label: "Currency",
        placeholder: {
          id: "pkcd514n25",
          label: "Currency",
        },
        optional: true,
        stringBefore: ',"currency":"',
        stringAfter: '"',
      },
      {
        id: "jcsf0zpcw5",
        type: "PLACEHOLDER",
        label: "Predicted Lifetime Value",
        placeholder: {
          id: "13c2mwza2a3b",
          label: "Predicted Lifetime Value",
        },
        optional: true,
        stringBefore: ',"predicted_ltv":"',
        stringAfter: '"',
      },
      {
        id: "t15mo5u5z7",
        type: "PLACEHOLDER",
        label: "Value",
        placeholder: {
          id: "wt1eu7kt45e",
          label: "Value",
        },
        optional: true,
        stringBefore: ',"value":"',
        stringAfter: '"',
      },
      {
        id: "er1hc0svuk",
        type: "PLACEHOLDER",
        label: "Content Type",
        placeholder: {
          id: "v09e2e6hc6h",
          label: "Content Type",
        },
        optional: true,
        stringBefore: ',"content_type":"',
        stringAfter: '"',
      },
      {
        id: "zw61uvu8mz",
        type: "TEXT",
        value: ",",
        label: ",",
        color: undefined,
      },
      {
        id: "njo8b0clmbl",
        type: "TEXT",
        value: '"content_ids":',
        label: '"content_ids":',
        color: undefined,
      },
      {
        id: "vup03o1q8u",
        type: "TEXT",
        value: "[",
        label: "[",
        color: "violet",
      },
      {
        id: "xe01e5f5bds",
        type: "PLACEHOLDER",
        label: "Product IDs",
        placeholder: {
          id: "ytrt0i6o0ym",
          label: "Product IDs",
        },
        optional: false,
        stringBefore: undefined,
        stringAfter: undefined,
      },
      {
        id: "76sepmw8wm4",
        type: "TEXT",
        value: "]",
        label: "]",
        color: "violet",
      },
      {
        id: "t1vwexe3fvi",
        type: "TEXT",
        value: ",",
        label: ",",
        color: undefined,
      },
      {
        id: "7tzvrdqnm6t",
        type: "TEXT",
        value: '"contents":',
        label: '"contents":',
        color: undefined,
      },
      {
        id: "os34n93345g",
        type: "TEXT",
        value: "[",
        label: "[",
        color: "violet",
      },
      {
        id: "9np1onp3ng",
        type: "PLACEHOLDER",
        label: "Product Info",
        placeholder: {
          id: "teq28fyvcr",
          label: "Product Info",
        },
        optional: false,
        stringBefore: undefined,
        stringAfter: undefined,
      },
      {
        id: "c8dnjzogssq",
        type: "TEXT",
        value: "]",
        label: "]",
        color: "violet",
      },
    ],
    childrenId: "fykx7w8nlna",
  },
  {
    id: "04ps9uqu6vkc",
    type: "TEXT",
    value: "}",
    label: "}",
    color: "red",
  },
  {
    id: "56oyd0h0ni7",
    type: "TEXT",
    value: "}",
    label: "}",
    color: "blue",
  },
  {
    id: "fb3it8phkbv",
    type: "TEXT",
    value: "]",
    label: "]",
    color: "orange",
  },
  {
    id: "qtpztdz0gw",
    type: "TEXT",
    value: "}",
    label: "}",
    color: undefined,
  },
];
